// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTouWElZJ3dY5xsF0-8ObQaclhPBewN3k',
    appId: '1:139807513811:web:7b54dbfe4db9053ecdc826',
    messagingSenderId: '139807513811',
    projectId: 'study-e7cce',
    authDomain: 'study-e7cce.firebaseapp.com',
    storageBucket: 'study-e7cce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ0mefRrgzDC4pMNTxsW2eEiBO4JOfZtY',
    appId: '1:139807513811:android:dc9d0a8f2b49a810cdc826',
    messagingSenderId: '139807513811',
    projectId: 'study-e7cce',
    storageBucket: 'study-e7cce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZXl5L55bvwnSsWGeu0Ti0xBXGB6-dKpw',
    appId: '1:139807513811:ios:85a91b8ac3513d36cdc826',
    messagingSenderId: '139807513811',
    projectId: 'study-e7cce',
    storageBucket: 'study-e7cce.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

}